## Section A: Data Structures & Control Structures

Q1:Create a list of 5 integers. Perform and print the result of the following operations: 
append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [3]:
#Append(): It will adds an element at the end of the list

numbers = [1,2,3,4]
numbers.append(5)
print(numbers)

[1, 2, 3, 4, 5]


In [4]:
#extend():It will adds elements from another list
a = [1,2]
b = [3,4]
a.extend(b)
print(a)

[1, 2, 3, 4]


In [5]:
#insert():insert an element at a specified index
nums = [10,20,30]
nums.insert(1,15)
print(nums)

[10, 15, 20, 30]


In [6]:
# Remove():It will removes the first occurence of specified values

nums = [10,20,"abc",30,40]
nums.remove(10)
print(nums)

[20, 'abc', 30, 40]


In [7]:
#pop():removes and returns an element (default last element will be remove)

data = [10,20,"Python",30,40.55]
data.pop()
print(data)

[10, 20, 'Python', 30]


In [8]:
#clear(): It will return empty list
lst = [1,2,3]
lst.clear()
print(lst)

[]


In [9]:
# index(): It will return the index of first occurenec of a value

nums = [10,20,30]
print(nums.index(20))

1


In [10]:
# Count() : Counts how many times value appears in datastructure

list_1 = [10,50,"WEB",89,100,50]
print(list_1.count(50))

2


In [11]:
# sort() : Sorts the data in ascending order(by default)
nums = [3,1,2,4,9,5]
nums.sort()
print(nums)

[1, 2, 3, 4, 5, 9]


In [13]:
# Reverse : value is reversed
nums =[1,2,3,4,5]
nums.reverse()
print(nums)

[5, 4, 3, 2, 1]


Q2.Create a tuple that stores 3 student names.
 Try changing the second name in the tuple. What happens? Explain why

In [30]:

students=["Amit", "Rahul","Dhanshri"]
print("Original Tuple:",students)

students[1]="Raya"

print("Updated Tuple:", students)

Original Tuple: ['Amit', 'Rahul', 'Dhanshri']
Updated Tuple: ['Amit', 'Raya', 'Dhanshri']


In [28]:
 #Step 1: Create a tuple with 3 student names
students = ("Amit", "Rahul", "Sneha")

print("Original Tuple:", students)

# Step 2: Try to change second name
students[1] = "Rohan"

print("Updated Tuple:", students)

Original Tuple: ('Amit', 'Rahul', 'Sneha')


TypeError: 'tuple' object does not support item assignment

Tuple is immutable when tuple is immutable then value is not chaged 
1 is updated tuple 
2 i can change tuple name but error is recongnize because of immutable tuple 

##= Q3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [33]:
numbers={8,1,2,10,3,7,2,5,4,6,9}
print("Set values:",numbers)

Set values: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


set is assending in order this is unorded structue (1,2,3,2,5,4,6,9,) and we got correct assending order [1,2,3,4,5,6,7,8,9,10]

Q4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. 
 Print the final dictionary

In [8]:
students= {
    "name":"Amit",
    "age":20,
    "city":"pune",
}
print(students)

{'name': 'Amit', 'age': 20, 'city': 'pune'}


In [5]:
students.keys()

dict_keys(['name', 'age', 'city'])

In [11]:
students.update({"name":"Dhanshri"})
students

{'name': 'Dhanshri', 'age': 20, 'city': 'pune'}

In [12]:
students.update({"age":"email"})
students

{'name': 'Dhanshri', 'age': 'email', 'city': 'pune'}

Q5.Write a script that checks if a person is eligible to vote (age ≥ 18).
   Take age as a variable and print the appropriate message

In [14]:
age = 20
if age > 18:
    print("You are eligible to vote")
else: 
    print("You are not eligible to vote")

You are eligible to vote


In [15]:
age = 17
if age > 18:
    print("You are eligible to vote")
else: 
    print("You are not eligible to vote")

You are not eligible to vote


Q6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [16]:
marks = 75

if marks >=90:
    print("Grade A")
elif marks >=75-89:
    print("Grade B")
elif marks >= 50-74:
    print("Grade C")
else:
    print("Fail")

Grade B


In [23]:
marks = 40

if marks >=90:
    print("Grade A")
elif marks >=75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

Fail


Q7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [4]:
number = int(input("Enter a number: "))

if number > 0:
    if number % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number:  2


The number is positive and even.


In [5]:
number = int(input("Enter a number: "))

if number > 0:
    if number % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number:  1


The number is positive but odd.


##=SECTION B - NUMPY

In [ ]:
Q8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [6]:
import numpy as np

In [8]:
age=np.array(5)
age

array(5)

In [10]:
# A 1d array with value 1 to 5 
age=np.array([[1],[2],[3],[4],[5]])
age

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
import numpy as np

arr = np.arange(10, 70, 10).reshape(2, 3)
arr

array([[10, 20, 30],
       [40, 50, 60]])

Q9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [19]:
#import numpy as np

# Generate 4x4 array with random integers from 0 to 100
arr = np.random.randint(0, 101, size=(4, 4))

arr

array([[84, 69, 64, 61],
       [89,  2, 89,  8],
       [54, 53, 91, 49],
       [83, 33, 13, 16]], dtype=int32)

Q10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [25]:
import numpy as np
import pandas as pd

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


##Section C: Exploring Pandas

Q11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [61]:
import pandas as pd
import numpy as np

# Create DataFrame manually
data = {
    'Name': ['John', 'Alice', 'Bob', 'David', 'Emma',
             'Frank', 'Grace', 'Henry', 'Ivy', 'John'],
    'Age': [25, 30, 22, 35, 28,
            40, 27, 32, 29, 25],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin',
             'Sydney', 'Toronto', 'Dubai', 'Rome', 'New York'],
    'Salary': [50000, 60000, np.nan, 80000, 75000,
               90000, np.nan, 65000, 70000, 50000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

Original DataFrame:
    Name  Age      City   Salary
0   John   25  New York  50000.0
1  Alice   30    London  60000.0
2    Bob   22     Paris      NaN
3  David   35     Tokyo  80000.0
4   Emma   28    Berlin  75000.0
5  Frank   40    Sydney  90000.0
6  Grace   27   Toronto      NaN
7  Henry   32     Dubai  65000.0
8    Ivy   29      Rome  70000.0
9   John   25  New York  50000.0


In [62]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [63]:
df.describe()

,Age,Salary
count,10.000000,8.000000
mean,29.300000,67500.000000
std,5.292552,14142.135624
min,22.000000,50000.000000
25%,25.500000,57500.000000
50%,28.500000,67500.000000
75%,31.500000,76250.000000
max,40.000000,90000.000000


In [65]:
selected_columns = df[['Name', 'City']]
print("\nSelected Columns (Name & City):")
print(selected_columns)


Selected Columns (Name & City):
    Name      City
0   John  New York
1  Alice    London
2    Bob     Paris
3  David     Tokyo
4   Emma    Berlin
5  Frank    Sydney
6  Grace   Toronto
7  Henry     Dubai
8    Ivy      Rome
9   John  New York


In [66]:
df = df.drop(columns=['City'])
print("\nAfter Dropping 'City' Column:")
print(df)


After Dropping 'City' Column:
    Name  Age   Salary
0   John   25  50000.0
1  Alice   30  60000.0
2    Bob   22      NaN
3  David   35  80000.0
4   Emma   28  75000.0
5  Frank   40  90000.0
6  Grace   27      NaN
7  Henry   32  65000.0
8    Ivy   29  70000.0
9   John   25  50000.0


In [67]:
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)

print("\nAfter Filling Missing Salary with Mean:")
print(df)


After Filling Missing Salary with Mean:
    Name  Age   Salary
0   John   25  50000.0
1  Alice   30  60000.0
2    Bob   22  67500.0
3  David   35  80000.0
4   Emma   28  75000.0
5  Frank   40  90000.0
6  Grace   27  67500.0
7  Henry   32  65000.0
8    Ivy   29  70000.0
9   John   25  50000.0


C:\Users\vinod\AppData\Local\Temp\ipykernel_10976\3699559105.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)


In [68]:
df = df.drop_duplicates()

print("\nAfter Removing Duplicates:")
print(df)


After Removing Duplicates:
    Name  Age   Salary
0   John   25  50000.0
1  Alice   30  60000.0
2    Bob   22  67500.0
3  David   35  80000.0
4   Emma   28  75000.0
5  Frank   40  90000.0
6  Grace   27  67500.0
7  Henry   32  65000.0
8    Ivy   29  70000.0


In [ ]:
###FINISH ##completed assignment no : 2 ; 